language: bash

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3.4 
  - |
      if [[ -n "$PYENV_VERSION" ]]; then
        wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
        source setup-pyenv.sh
      fi

before_script:
  - mkdir nexus5 && mkdir -p NEXUS5 && chmod +x *.sh && cp hadk.env ~/.hadk.env

script:
  - bash -x ./fullbuild.sh
